<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Motor.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Motor.Aplicacao\Motor.Aplicacao.csproj" />
    <ProjectReference Include="..\Motor.Infraestrutura\Motor.Infraestrutura.csproj" />
  </ItemGroup>
</Project>
